version: "3.1"
services:
  postgres:
    image: postgres:11-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: web4321
      POSTGRES_USER: web4321
      POSTGRES_DB: tododb
    ports:
      - 5432:5432
